# 机场订阅
pp: &pp {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, interval: 30, url: "https://www.gstatic.com/generate_204"}, header: {User-Agent: ["Clash/v1.18.0", "mihomo/1.19.19"]}, override: {client-fingerprint: chrome}}
proxy-providers:
  BPB:
    <<: *pp
    url: "https://bpb.seaspirit.dpdns.org/sub/normal/de5eb6ed-ceee-4de9-b5a5-7ee799dc99aa?app=clash#%F0%9F%92%A6%20BPB%20Normal"
# 全局配置 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
# 控制面板
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
# 入站  
tun:
  enable: true
  stack: mixed # system/gvisor/mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  listen: 0.0.0.0:1053
  ipv6: true
  ipv6-timeout: 300
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.subhd.*"
    - "+.yysub.*"
    - "+.torrentgalaxy.one"
    - "+.torrentdownloads.pro"
    - "+.returnyoutubedislikeapi.com"
    - rule-set:cn_domain
    - rule-set:fakeipfilter_domain
    - rule-set:category-ai-!cn_domain
    - rule-set:category-ai-cn_domain
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:google_domain,reddit_domain,category-porn_domain,gfw_domain,geolocation-!cn,netflix_domain,microsoft_domain":
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query
    "rule-set:bytedance_domain,bytedance@!cn_domain":
      - 180.184.1.1
      - 223.5.5.5
    "rule-set:huawei_domain":
      - '1.1.1.1#DIRECT'
      - 223.5.5.5
    "rule-set:tencent_domain":
      - 119.29.29.29
      - 223.5.5.5
# 出站策略
pg: &pg {type: url-test, interval: 30, tolerance: 1, include-all: true}
proxy-groups:
  - {name: Auto, <<: *pg}
  - {name: Domain, <<: *pg, filter: "(?i)Domain"}
  - {name: IPv4, <<: *pg, filter: "(?i)IPv4"}
  - {name: IPv6, <<: *pg, filter: "(?i)IPv6"}
  - {name: VLESS, <<: *pg, filter: "(?i)VLESS"}
  - {name: Trojan, <<: *pg, filter: "(?i)Trojan"}
  - {name: BPB, <<: *pg, filter: "^((?!(Clean IP)).)*$"}
  - {name: Clean IPs, <<: *pg, filter: "(?i)Clean IP"}
# 规则匹配
rules:
  - DOMAIN-SUFFIX,amemv.com,Auto
  - RULE-SET,google@ads,REJECT-DROP
  - RULE-SET,google_domain,Auto
  - RULE-SET,cloudflare_domain,DIRECT
  - RULE-SET,bytedance@ads,REJECT-DROP
  - RULE-SET,bytedance@!cn_domain,Auto
  - RULE-SET,bytedance_domain,DIRECT
  - RULE-SET,github_domain,Auto
  - RULE-SET,category-ai-!cn@ads,REJECT-DROP
  - RULE-SET,category-ai-!cn_domain,Auto
  - RULE-SET,category-ai-cn_domain,Auto
  - RULE-SET,microsoft@ads,REJECT-DROP
  - RULE-SET,microsoft_domain,Auto
  - RULE-SET,apple@ads,REJECT-DROP
  - RULE-SET,apple_domain,DIRECT
  - RULE-SET,huawei_domain,DIRECT
  - RULE-SET,alibaba_domain,DIRECT
  - RULE-SET,tencent_domain,DIRECT
  - RULE-SET,netflix_domain,Auto
  - RULE-SET,disney_domain,Auto
  - RULE-SET,telegram_domain,Auto
  - RULE-SET,speedtest_domain,Auto
  - RULE-SET,paypal_domain,Auto
  - RULE-SET,test-ipv6_domain,DIRECT
  - DOMAIN-KEYWORD,subhd,DIRECT
  - DOMAIN-KEYWORD,uupdump,DIRECT
  - DOMAIN-SUFFIX,returnyoutubedislikeapi.com,DIRECT
  - DOMAIN-SUFFIX,seaspirit.dpdns.org,DIRECT
  - DOMAIN-SUFFIX,qnap.com,DIRECT
  - DOMAIN-SUFFIX,downloadtorrentfile.com,DIRECT
  - DOMAIN-SUFFIX,softonic.cn,Auto
  - RULE-SET,reddit_domain,Auto
  - RULE-SET,category-porn@ads,REJECT-DROP
  - RULE-SET,category-porn_domain,Auto
  - RULE-SET,gfw_domain,Auto
  - RULE-SET,geolocation-!cn,Auto
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,google_ip,Auto,no-resolve
  - RULE-SET,cloudflare_ip,Auto,no-resolve
  - RULE-SET,netflix_ip,Auto,no-resolve
  - RULE-SET,telegram_ip,Auto,no-resolve
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve
  - MATCH,Auto
# 规则集
rule-anchor:
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
rule-providers:
  # 分隔,下面是DOMAIN分组
  fakeipfilter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  google@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google@ads.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  cloudflare_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.mrs"}
  category-ai-!cn@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn@ads.mrs" }
  category-ai-!cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  category-ai-cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-cn.mrs" }
  bytedance@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance@ads.mrs"}
  bytedance@!cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance@!cn.mrs"}
  bytedance_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  microsoft@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@ads.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple@ads.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  huawei_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/huawei.mrs"}
  alibaba_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/alibaba.mrs"}
  tencent_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tencent.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  test-ipv6_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/test-ipv6.mrs"}
  reddit_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/reddit.mrs"}
  category-porn@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn@ads.mrs"}
  category-porn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"} 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  # 分隔,下面是IP分组
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  cloudflare_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  private_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}