# æœºåœºè®¢é˜…
proxy-providers:
  å±±æ°´äº‘:
    url: "https://su.xfjhchr.com:8888/api/v1/client/subscribe?token=35ed675d0e2e1ae13cb0366a03408258"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 30
    proxy: DIRECT
  GFWAirPort:
    url: "https://www9th.ga-sub.baby/api/v1/client/subscribe?token=3d36b6d2b1d958987ee709354d9ebb94"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 30
    proxy: DIRECT
    override:
      skip-cert-verify: true
# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: en0
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/nikki/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
# å…¥ç«™  
tun:
  enable: true
  stack: mixed # system/gvisor/mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  nameserver: # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
    - system
  proxy-server-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver-policy:
    "api6-normal-lf.amemv.com":
      - '180.184.1.1#ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹'
      - '180.184.2.2#ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹'
    "rule-set:bytedance@!cn_domain":
      - 1.1.1.1
      - 1.0.0.1
    "rule-set:bytedance_domain":
      - 180.184.1.1
      - 180.184.2.2
    "www.youtube.com,www.google.com":
      - 8.8.8.8
      - 8.8.4.4
    "rule-set:google_domain":
      - 8.8.8.8
      - 8.8.4.4
    "rule-set:category-ai-!cn_domain,microsoft_domain,apple_domain,netflix_domain,disney_domain,geolocation-!cn,gfw_domain":
      - 1.1.1.1
      - 1.0.0.1
    "rule-set:github_domain,telegram_domain,speedtest_domain,paypal_domain,reddit_domain,category-porn_domain":
      - 1.1.1.1
      - 1.0.0.1
    "MATCH":
      - 1.1.1.1
      - 1.0.0.1
# å‡ºç«™ç­–ç•¥
pr: &pr {type: url-test, include-all: true, tolerance: 1}
pr2: &pr2 {type: url-test, tolerance: 1, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹]}
proxy-groups:
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, !!merge <<: *pr, filter: "æ¸¯|HK|(?i)Hong"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, !!merge <<: *pr, filter: "å°|TW|(?i)Taiwan"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, !!merge <<: *pr, filter: "æ—¥|JP|(?i)Japan|Tokyo"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, !!merge <<: *pr, filter: "éŸ©|KR|(?i)Korea|Incheon"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, !!merge <<: *pr, filter: "æ–°|ç‹®|SG|(?i)Singapore"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, !!merge <<: *pr, filter: "ç¾|US|(?i)States|America|California"}
  - {name: ğŸš€ è‡ªåŠ¨é€‰æ‹©, !!merge <<: *pr}
  - {name: ğŸ“½ï¸ TikTok, type: url-test, tolerance: 1, proxies: [ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹]}
  - {name: ğŸ¥ NETFLIX, !!merge <<: *pr2}
  - {name: ğŸ“¹ Disney+, !!merge <<: *pr2}
# è§„åˆ™åŒ¹é…
rules:
  - DOMAIN,api6-normal-lf.amemv.com,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹ # ç”¨äºæŒ‡å®šæŠ–éŸ³çš„çœ(å¸‚/åŒº)
  - DOMAIN,www.youtube.com,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ # ç”¨äºæŒ‡å®šæ²¹ç®¡çš„å›½å®¶/åœ°åŒº
  - DOMAIN,www.google.com,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ # ç”¨äºæŒ‡å®šè°·æ­Œæœç´¢çš„å›½å®¶/åœ°åŒº  
  - RULE-SET,google@ads,REJECT-DROP  
  - RULE-SET,google_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©  
  - RULE-SET,bytedance@ads,REJECT-DROP  
  - RULE-SET,bytedance@!cn_domain,ğŸ“½ï¸ TikTok
  - RULE-SET,bytedance_domain,DIRECT
  - RULE-SET,github_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©  
  - RULE-SET,category-ai-!cn@ads,REJECT-DROP  
  - RULE-SET,category-ai-!cn_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,category-ai-cn_domain,DIRECT  
  - RULE-SET,microsoft@ads,REJECT-DROP  
  - RULE-SET,onedrive_domain,DIRECT
  - RULE-SET,microsoft_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©  
  - RULE-SET,apple@ads,REJECT-DROP  
  - RULE-SET,apple-cn_domain,DIRECT
  - RULE-SET,apple@cn_domain,DIRECT
  - RULE-SET,apple_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,disney_domain,ğŸ“¹ Disney+
  - RULE-SET,telegram_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,speedtest_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,paypal_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,test-ipv6_domain,DIRECT
  - DOMAIN-SUFFIX,com.tw,ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
  - DOMAIN-SUFFIX,co.jp,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,qnap.com,DIRECT
  - DOMAIN-SUFFIX,softonic.cn,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,reddit_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©  
  - RULE-SET,category-porn@ads,REJECT-DROP  
  - RULE-SET,category-porn_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,gfw_domain,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,geolocation-!cn,ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,google_ip,ğŸš€ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸš€ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,private_ip,DIRECT
  - MATCH,ğŸš€ è‡ªåŠ¨é€‰æ‹©
# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
# DOMAIN
  google@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google@ads.mrs"}
  google_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google.mrs"}
  category-ai-!cn@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn@ads.mrs" }
  category-ai-!cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs" }
  category-ai-cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-cn.mrs" }
  bytedance@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bytedance@ads.mrs"}
  bytedance@!cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bytedance@!cn.mrs"}
  bytedance_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bytedance.mrs"}
  github_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/github.mrs"}
  telegram_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/netflix.mrs"}
  disney_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/disney.mrs"}
  paypal_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/paypal.mrs"}
  microsoft@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/microsoft@ads.mrs"}
  onedrive_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/microsoft.mrs"}
  apple@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple@ads.mrs"}
  apple-cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple-cn.mrs"}
  apple@cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple@cn.mrs"}
  apple_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/ookla-speedtest.mrs"}
  test-ipv6_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/test-ipv6.mrs"}
  reddit_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs"}
  category-porn@ads: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-porn@ads.mrs"}
  category-porn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-porn.mrs"}
  gfw_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cn.mrs"} 
  private_domain: { !!merge <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/private.mrs"}
# IP
  google_ip: { !!merge <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/google.mrs"}
  telegram_ip: { !!merge <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { !!merge <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/netflix.mrs"}
  cn_ip: { !!merge <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cn.mrs"}
  private_ip: { !!merge <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/private.mrs"}