# æœºåœºè®¢é˜…
proxy-providers:
  GFWAirPort:
    url: "https://www9th.ga-sub.baby/api/v1/client/subscribe?token=3d36b6d2b1d958987ee709354d9ebb94"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 15
    proxy: DIRECT
    override:
      skip-cert-verify: true
  Flower_Trojan:
    url: "https://api.xmancdn.com/osubscribe.php?sid=114693&token=A0QNsMcM"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 15
    proxy: DIRECT
# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: en0
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"
# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  nameserver:  # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
    - 202.102.152.3
    - 202.102.154.3 
# å‡ºç«™ç­–ç•¥
pr: &pr {type: url-test, tolerance: 1, interval: 15, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹]}
proxy-groups:
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 1, interval: 15}
  - {name: ChatGPT, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/openai.com/chatgpt.svg"}
  - {name: YouTube, type: fallback, interval: 15, proxies: [â–¶ï¸ æµåª’ä½“ä¸“ç”¨èŠ‚ç‚¹, â™»ï¸ è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/youtube.com/youtube.svg"}
  - {name: Google, type: fallback, interval: 15, proxies: [ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, â™»ï¸ è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/google.com/google.svg"}
  - {name: æŠ–éŸ³, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "^((?!(æ—¥æœ¬|Tokyo|éŸ©å›½|Incheon|å‰©ä½™|åˆ°æœŸ)).)*$", icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/tiktok.com/tiktok.svg"}
  - {name: TikTok, type: url-test, tolerance: 1, interval: 15, proxies: [ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹], icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/tiktok.com/tiktok.svg"}
  - {name: GitHub, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/github.com/github-icon-light.svg"}
  - {name: Telegram, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/telegram.com/telegram-plane.svg"}
  - {name: Microsoft, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/microsoft.com/microsoft.svg"}
  - {name: OneDrive, type: select, interval: 15, proxies: [DIRECT, â™»ï¸ è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/microsoft.com/microsoft-onedrive.svg"}
  - {name: Netflix, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/netflix.com/netflix.svg"}
  - {name: Disney+, <<: *pr, icon: "https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Large/Disney_plus.png"}
  - {name: è‹¹æœ, type: select, interval: 15, proxies: [DIRECT, â™»ï¸ è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/apple.com/apple.svg"}
  - {name: Apple, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/apple.com/apple.svg"}
  - {name: PayPal, <<: *pr, icon: "https://raw.githubusercontent.com/raivo-otp/issuer-icons/refs/heads/master/vectors/paypal.com/paypal.svg"}
  - {name: SpeedTest, <<: *pr, icon: "https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Large/SpeedTest.png"}
  - {name: ğŸª æ¼ç½‘ä¹‹é±¼, <<: *pr}
  - name: "â–¶ï¸ æµåª’ä½“ä¸“ç”¨èŠ‚ç‚¹"
    type: url-test
    use:
      - GFWAirPort
    tolerance: 1
    interval: 15
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)å°|TW|Taiwan"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)æ—¥|jp|japan|Tokyo"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)éŸ©|KR|Korea|Incheon"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)æ–°|ç‹®|SG|Singapore"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: url-test, include-all: true, tolerance: 1, interval: 15, filter: "(?i)ç¾|us|unitedstates|united states|California"}
# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,category-ads-all_domain,REJECT
  - DOMAIN,www.youtube.com,Google
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google-play_domain,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,google_domain,Google
  - RULE-SET,bytedance@!cn_domain,TikTok
  - RULE-SET,bytedance_domain,æŠ–éŸ³
  - RULE-SET,github_domain,GitHub
  - RULE-SET,category-ai-!cn_domain,ChatGPT
  - RULE-SET,onedrive_domain,OneDrive
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,apple-cn_domain,è‹¹æœ
  - RULE-SET,apple@cn_domain,è‹¹æœ
  - RULE-SET,apple_domain,Apple
  - RULE-SET,netflix_domain,Netflix
  - RULE-SET,disney_domain,Disney+
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,speedtest_domain,SpeedTest
  - RULE-SET,paypal_domain,PayPal
  - RULE-SET,test-ipv6_domain,DIRECT
  - DOMAIN-SUFFIX,jp,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,qnap.com,DIRECT
  - DOMAIN-SUFFIX,softonic.cn,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,gfw_domain,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,geolocation-!cn,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,netflix_ip,Netflix,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,private_ip,DIRECT
  - MATCH,ğŸª æ¼ç½‘ä¹‹é±¼
# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
# DOMAIN
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  category-ads-all_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all.mrs"} 
  google-play_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-play.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  category-ai-!cn_domain: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple-cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  apple@cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple@cn.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  bytedance@!cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance@!cn.mrs"}
  bytedance_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bytedance.mrs"}
  test-ipv6_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/test-ipv6.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"} 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
# IP
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"} 
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  private_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}