# æœºåœºè®¢é˜…
pp: &pp {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, interval: 300, url: "https://www.gstatic.com/generate_204"}}
proxy-providers:
  å±±æ°´äº‘:
    url: "https://su.xfjhchr.com:8888/api/v1/client/subscribe?token=35ed675d0e2e1ae13cb0366a03408258"
    <<: *pp
  GFWAirPort:
    url: "https://www9th.ga-sub.baby/api/v1/client/subscribe?token=3d36b6d2b1d958987ee709354d9ebb94"
    <<: *pp
    override:
      skip-cert-verify: true
# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: en0
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
# æŽ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/nikki/run"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# å—…æŽ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
# å…¥ç«™  
tun:
  enable: true
  stack: mixed # system/gvisor/mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver: # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
    - 202.102.128.68
    - 202.102.134.68
  proxy-server-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver-policy:
    "api6-normal-lf.amemv.com":
      - 202.102.128.68
      - 202.102.134.68
    "www.youtube.com,www.google.com":
      - 8.8.8.8
      - 8.8.4.4
    "rule-set:google-play_domain,google_domain":
      - 8.8.8.8
      - 8.8.4.4
    "rule-set:category-ai-!cn_domain,bytedance@!cn_domain,netflix_domain,disney_domain,geolocation-!cn,gfw_domain":
      - 1.1.1.1
      - 1.0.0.1
    "rule-set:github_domain,telegram_domain,speedtest_domain,paypal_domain,reddit_domain,category-porn_domain":
      - https://1.1.1.1/dns-query
    "MATCH":
      - https://1.1.1.1/dns-query
# å‡ºç«™ç­–ç•¥
pr: &pr {type: url-test, interval: 300, tolerance: 1, include-all: true}
pr2: &pr2 {type: url-test, interval: 300, tolerance: 1, lazy: false, proxies: [ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ðŸ‡¹ðŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ðŸ‡¯ðŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ðŸ‡°ðŸ‡· éŸ©å›½èŠ‚ç‚¹, ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹]}
proxy-groups:
  - {name: ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹, <<: *pr, filter: "æ¸¯|HK|(?i)HongXX"}
  - {name: ðŸ‡¹ðŸ‡¼ å°æ¹¾èŠ‚ç‚¹, <<: *pr, filter: "å°|TW|(?i)Taiwan"}
  - {name: ðŸ‡¯ðŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, <<: *pr, filter: "æ—¥|JP|(?i)Japan|Tokyo"}
  - {name: ðŸ‡°ðŸ‡· éŸ©å›½èŠ‚ç‚¹, <<: *pr, filter: "éŸ©|KR|(?i)Korea|Incheon"}
  - {name: ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, <<: *pr, filter: "æ–°|ç‹®|SG|(?i)Singapore"}
  - {name: ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, <<: *pr, filter: "ç¾Ž|US|(?i)States|America|California"}
  - {name: ðŸš€ è‡ªåŠ¨é€‰æ‹©, type: load-balance, strategy: consistent-hashing, interval: 300, include-all: true}
  - {name: ðŸ“½ï¸ TikTok, type: url-test, tolerance: 1, proxies: [ðŸ‡¹ðŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ðŸ‡¯ðŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ðŸ‡°ðŸ‡· éŸ©å›½èŠ‚ç‚¹, ðŸ‡¸ðŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹]}
  - {name: ðŸŽ¥ NETFLIX, <<: *pr2}
  - {name: ðŸ“¹ Disney+, <<: *pr2}
# è§„åˆ™åŒ¹é…
rules:
  - DOMAIN,api6-normal-lf.amemv.com,ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹ # ç”¨äºŽæŒ‡å®šæŠ–éŸ³çš„çœ(å¸‚/åŒº)
  - DOMAIN,www.youtube.com,ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹ # ç”¨äºŽæŒ‡å®šæ²¹ç®¡çš„å›½å®¶/åœ°åŒº
  - DOMAIN,www.google.com,ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹ # ç”¨äºŽæŒ‡å®šè°·æ­Œæœç´¢çš„å›½å®¶/åœ°åŒº
  - RULE-SET,google-play_domain,ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - RULE-SET,google@ads,REJECT-DROP
  - RULE-SET,google_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,bytedance@ads,REJECT-DROP
  - RULE-SET,bytedance@!cn_domain,ðŸ“½ï¸ TikTok
  - RULE-SET,github_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,category-ai-!cn@ads,REJECT-DROP
  - RULE-SET,category-ai-!cn_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹© 
  - RULE-SET,microsoft@ads,REJECT-DROP
  - RULE-SET,microsoft_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,apple@ads,REJECT-DROP
  - RULE-SET,apple_domain,DIRECT
  - RULE-SET,netflix_domain,ðŸŽ¥ NETFLIX
  - RULE-SET,disney_domain,ðŸ“¹ Disney+
  - RULE-SET,telegram_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,speedtest_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,paypal_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,test-ipv6_domain,DIRECT
  - DOMAIN-SUFFIX,jp,ðŸ‡¯ðŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,tw,ðŸ‡¹ðŸ‡¼ å°æ¹¾èŠ‚ç‚¹
  - DOMAIN-SUFFIX,us,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,qnap.com,DIRECT
  - DOMAIN-SUFFIX,softonic.cn,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,reddit_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,category-porn@ads,REJECT-DROP
  - RULE-SET,category-porn_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,gfw_domain,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,geolocation-!cn,ðŸš€ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,google_ip,ðŸš€ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - RULE-SET,netflix_ip,ðŸŽ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ðŸš€ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,private_ip,DIRECT
  - MATCH,ðŸš€ è‡ªåŠ¨é€‰æ‹©
# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
# DOMAIN
  google@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google@ads.mrs"}
  google-play_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google-play.mrs"}
  google_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google.mrs"}
  category-ai-!cn@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn@ads.mrs" }
  category-ai-!cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs" }
  bytedance@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bytedance@ads.mrs"}
  bytedance@!cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bytedance@!cn.mrs"}
  github_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/disney.mrs"}
  paypal_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/paypal.mrs"}
  microsoft@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/microsoft@ads.mrs"}
  microsoft_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/microsoft.mrs"}
  apple@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple@ads.mrs"}
  apple_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/ookla-speedtest.mrs"}
  test-ipv6_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/test-ipv6.mrs"}
  reddit_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs"}
  category-porn@ads: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-porn@ads.mrs"}
  category-porn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-porn.mrs"}
  gfw_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cn.mrs"} 
  private_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/private.mrs"}
# IP
  google_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/netflix.mrs"}
  cn_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cn.mrs"}
  private_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/private.mrs"}